theme: minima
title: Welcome! 👋≧◉ᴥ◉≦
author: LohikäärmeDigital 
email: ryzensynth3100@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my site! I'm glad you joined me here! I'm a first time Github user and looking forward to learn more and contribute to Github.

# social links
twitter_username: KlausSynth # DO NOT include the @ character, or else the build will fail!
github_username:  LohikäärmeDigital  # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
